### ISSUE TITLE
Help command usage is wrong

### ISSUE THREAD

**Issue by swerner** [sublayerapp/sublayer#102]
![image](https://github.com/user-attachments/assets/68cd22a3-3380-413f-830a-b36e570885bf)

For some reason thor is generating the command usage as `sublayer sublayer:commands:new` and `sublayer sublayer:commands:generator` which isn't right. 

Need to figure out how to override the default usage string there as the plain `sublayer` command does output them correctly.

**Comment by AndrewBKang** [comment]
will be fixed on next patch
