### ISSUE TITLE
Broken links on documentation home 

### ISSUE THREAD

**Issue by rosalynnas** [sublayerapp/sublayer#116]
The links on the documentation home page are not working. For example, the "Quick start" link is:
* https://docs.sublayer.com/docs/quick/_start.md

But the working sidebar link is:
* https://docs.sublayer.com/docs/quick_start/

Every link apart from "View on GitHub" returns a 404

**Comment by swerner** [comment]
Thanks so much for catching and reporting this! We just moved over to a new docs site and looks like we missed updating the link format on these.

Just deployed a fix!
