### ISSUE TITLE
Occasional 500 errors from newer gemini models

### ISSUE THREAD

**Issue by swerner** [sublayerapp/sublayer#46]
Started working on adding the list_of_strings output adapter, and along the way updated the gemini provider to use the function calling syntax that should be enabled on the latest models:
`gemini-1.0-pro`
`gemini-1.0-pro-001`
`gemini-1.5-flash-latest`
`gemini-1.5-pro-latest`
as described here: https://ai.google.dev/gemini-api/docs/function-calling

Have to do multiple calls to get it to respond with something other than 500, and occasionally it doesn't actually do a function call and just returns a text response.

**Comment by AndrewBKang** [comment]
The weirdest thing... 
the tests pass in sublayer if I simply remove the line: "Take a deep breath and think step by step before you start coding." from the example generator

**Comment by swerner** [comment]
Oh that's super interesting!

**Comment by AndrewBKang** [comment]
So I was wondering if it had to do with the sentence itself. Tried it on historical event generator but it's working fine. so it might not be the content of the sentence. I'm wondering if it's the size of the text now. Going to see what the default context window is for gemini. and then play with the size of the text in the prompt.

**Comment by swerner** [comment]
Still getting issues here across the board even as we add additional output adapters. I'll keep digging to try to find a way to bring gemini back...

**Comment by swerner** [comment]
spent a bunch of time generating with the new gemini provider, this will be fixed in the 0.2.5 release

**Comment by swerner** [comment]
Fixed as of `0.2.5`
